### ISSUE TITLE
Deploy on Heroku

### ISSUE THREAD

**Issue by Mohammadjoon1453** [sentrionic/Valkyrie#15]
Hi fist of all thanks for this fantastic app 
the question is how can I deploy this Golang server on Heroku ?
could u explain that plz ?

**Comment by sentrionic** [comment]
Depends on if you want to manually upload to Heroku using the CLI or on push like in this repository.
But the basic steps are:
1. Create app on Heroku
2. Add a Postgres and Redis add-on in the resource tab
3. In the settings tab add the vars `AWS_ACCESS_KEY`, `AWS_S3_REGION`, `AWS_SECRET_ACCESS_KEY`, `AWS_STORAGE_BUCKET_NAME`, `CORS_ORIGIN`, `DOMAIN`, `GIN_MODE` release, `GMAIL_PASSWORD`, `GMAIL_USER`, `HANDLER_TIMEOUT` 5, `MAX_BODY_BYTES` 4194304 and `SECRET`. Gmail and AWS can be any strings if you don't need them.
4. Upload the backend (CLI: You need to push a sub directory. Github Action: You need to add environment variables to your repository)

Note that if you also want to host the frontend then you will need to add a custom domain since cookies only work on websites with the same domain name. And Heroku only allows that on paid dynos.

**Comment by Mohammadjoon1453** [comment]
ok and what should i do with this one that gave me in Config Vars postgres://exhdrXXXnwyyukwq:aXXXf9XXXXXXXXXXX ?

**Comment by sentrionic** [comment]
Heroku automatically sets that and the Redis one, you don't need to change anything.

**Comment by Mohammadjoon1453** [comment]
alright thanks for replying <3
